export type TDeviceId =
  | "iphone-14"
  | "iphone-14-pro"
  | "iphone-x"
  | "iphone-8"
  | "the-iphone"
  | "google-pixel-6-pro"
  | "google-pixel-2-xl"
  | "google-pixel"
  | "galaxy-s8"
  | "ipad-pro"
